In [85]:
import svm
from imp import reload
import numpy as np
reload(svm)

<module 'svm' from 'D:\\CPU_Manny\\workspace\\DeepLearning\\MachineLearningInAction\\Ch06\\svm.py'>

In [30]:
dataMatrix,labelMatrix=svm.loadDataSet('testSet.txt')

In [31]:
b,alphas= svm.simplifiedSmo(dataMatrix,labelMatrix,0.6, 0.001, 40)

L==H
L==H
L==H
L==H
iter: 0 i: 4,pairs changed 1
iter: 0 i: 5,pairs changed 2
L==H
L==H
j not moving enough
L==H
iter: 0 i: 13,pairs changed 3
iter: 0 i: 17,pairs changed 4
j not moving enough
j not moving enough
L==H
j not moving enough
j not moving enough
L==H
j not moving enough
j not moving enough
L==H
L==H
L==H
iter: 0 i: 54,pairs changed 5
L==H
j not moving enough
j not moving enough
j not moving enough
L==H
j not moving enough
L==H
L==H
j not moving enough
j not moving enough
j not moving enough
iter num is: 0
j not moving enough
L==H
j not moving enough
j not moving enough
iter: 0 i: 7,pairs changed 1
L==H
L==H
L==H
j not moving enough
iter: 0 i: 17,pairs changed 2
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iter num is: 0
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iter: 0 i: 71,pairs cha

j not moving enough
iter: 0 i: 29,pairs changed 1
iter: 0 i: 46,pairs changed 2
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iter: 0 i: 97,pairs changed 3
iter num is: 0
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iter num is: 1
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iter num is: 2
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iter: 2 i: 69,pairs changed 1
iter num is: 0
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iter num is: 1
j not moving enough
j not moving enough
j not moving enough
iter: 1 i: 29,pairs chang

j not moving enough
j not moving enough
j not moving enough
iter num is: 13
j not moving enough
j not moving enough
j not moving enough
iter num is: 14
j not moving enough
j not moving enough
j not moving enough
iter num is: 15
j not moving enough
j not moving enough
j not moving enough
iter num is: 16
j not moving enough
j not moving enough
j not moving enough
iter num is: 17
j not moving enough
j not moving enough
j not moving enough
iter num is: 18
j not moving enough
j not moving enough
j not moving enough
iter num is: 19
j not moving enough
j not moving enough
j not moving enough
iter num is: 20
j not moving enough
j not moving enough
j not moving enough
iter num is: 21
j not moving enough
j not moving enough
j not moving enough
iter num is: 22
j not moving enough
j not moving enough
j not moving enough
iter num is: 23
j not moving enough
j not moving enough
j not moving enough
iter num is: 24
j not moving enough
j not moving enough
j not moving enough
iter num is: 25
j not moving

iter: 7 i: 23,pairs changed 2
j not moving enough
j not moving enough
iter num is: 0
j not moving enough
j not moving enough
j not moving enough
iter num is: 1
j not moving enough
j not moving enough
j not moving enough
iter num is: 2
j not moving enough
iter: 2 i: 29,pairs changed 1
j not moving enough
j not moving enough
iter num is: 0
j not moving enough
j not moving enough
j not moving enough
iter num is: 1
j not moving enough
j not moving enough
j not moving enough
iter num is: 2
j not moving enough
j not moving enough
j not moving enough
iter num is: 3
j not moving enough
j not moving enough
j not moving enough
iter num is: 4
j not moving enough
j not moving enough
j not moving enough
iter num is: 5
j not moving enough
j not moving enough
j not moving enough
iter num is: 6
j not moving enough
j not moving enough
j not moving enough
iter num is: 7
j not moving enough
j not moving enough
iter: 7 i: 55,pairs changed 1
iter num is: 0
j not moving enough
j not moving enough
j not movi

In [32]:
dataMatrix=np.mat(dataMatrix)

In [33]:
type(dataMatrix)

numpy.matrixlib.defmatrix.matrix

In [34]:
a=np.mat(dataMatrix[1,:]).transpose

In [35]:
type(dataMatrix.transpose())

numpy.matrixlib.defmatrix.matrix

In [36]:
b

matrix([[-3.79018279]])

In [37]:
alphas[alphas>0]

matrix([[ 0.16503477,  0.11496949,  0.08488298,  0.36488724]])

In [38]:
data = np.mat([[1,0,1],[0,0,1]])

In [39]:
np.nonzero(data)[0]

array([0, 0, 1], dtype=int32)

In [40]:
np.nonzero(data.getA())[0]

array([0, 0, 1], dtype=int32)

In [41]:
import svm

In [62]:
dataArr,labelArr = svm.loadDataSet('testSet.txt')

In [63]:
b,alphas = svm.smoP(dataArr, labelArr, 0.6, 0.001, 40)

L==H
L==H
L==H
L==H
L==H
j not moving enough
fullSet,iter: 0 i: 99, pairs changed 5
iternation num :1
nonBoundIS, iter :1 i: 8,pairs changed 1
nonBoundIS, iter :1 i: 10,pairs changed 2
j not moving enough
nonBoundIS, iter :1 i: 52,pairs changed 2
nonBoundIS, iter :1 i: 54,pairs changed 3
nonBoundIS, iter :1 i: 55,pairs changed 4
iternation num :2
j not moving enough
nonBoundIS, iter :2 i: 8,pairs changed 0
j not moving enough
nonBoundIS, iter :2 i: 17,pairs changed 0
j not moving enough
nonBoundIS, iter :2 i: 29,pairs changed 0
nonBoundIS, iter :2 i: 52,pairs changed 0
j not moving enough
nonBoundIS, iter :2 i: 54,pairs changed 0
nonBoundIS, iter :2 i: 55,pairs changed 0
iternation num :3
j not moving enough
j not moving enough
j not moving enough
j not moving enough
fullSet,iter: 3 i: 99, pairs changed 0
iternation num :4


In [56]:
a = np.mat([1,2,3,4,5])

In [57]:
a

matrix([[1, 2, 3, 4, 5]])

In [58]:
np.nonzero((a>2) * (a<6))[0]

ValueError: shapes (1,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

In [66]:
ws = svm.calcWs(alphas, dataArr, labelArr)

In [67]:
ws

array([[ 0.79217255],
       [-0.25433037]])

In [68]:
dataMatrix = np.mat(dataArr)

In [71]:
dataMatrix[2]*ws + b

matrix([[ 2.67362096]])

In [115]:
import svm
from imp import reload
import numpy as np
reload(svm)

<module 'svm' from 'D:\\CPU_Manny\\workspace\\DeepLearning\\MachineLearningInAction\\Ch06\\svm.py'>

In [116]:
svm.testRbf()

L==H
j not moving enough
j not moving enough
j not moving enough
L==H
L==H
L==H
j not moving enough
L==H
j not moving enough
L==H
L==H
L==H
L==H
L==H
L==H
L==H
fullSet,iter: 0 i: 99, pairs changed 28
iternation num :1
j not moving enough
nonBoundIS, iter :1 i: 0,pairs changed 0
j not moving enough
nonBoundIS, iter :1 i: 1,pairs changed 0
j not moving enough
nonBoundIS, iter :1 i: 3,pairs changed 0
j not moving enough
nonBoundIS, iter :1 i: 10,pairs changed 0
j not moving enough
nonBoundIS, iter :1 i: 11,pairs changed 0
j not moving enough
nonBoundIS, iter :1 i: 13,pairs changed 0
j not moving enough
nonBoundIS, iter :1 i: 14,pairs changed 0
j not moving enough
nonBoundIS, iter :1 i: 15,pairs changed 0
j not moving enough
nonBoundIS, iter :1 i: 16,pairs changed 0
j not moving enough
nonBoundIS, iter :1 i: 17,pairs changed 0
j not moving enough
nonBoundIS, iter :1 i: 18,pairs changed 0
j not moving enough
nonBoundIS, iter :1 i: 19,pairs changed 0
nonBoundIS, iter :1 i: 21,pairs changed 0

In [94]:
from math import exp

In [95]:
exp

<function math.exp>

In [114]:
from math import sign

ImportError: cannot import name 'sign'