In [1]:
names = ['a', 'b','a']
namesset=set(names)


In [2]:
namesset

{'a', 'b'}

In [7]:
help(set.remove)


Help on method_descriptor:

remove(...)
    Remove an element from a set; it must be a member.
    
    If the element is not a member, raise a KeyError.



In [8]:
help(set.discard)

Help on method_descriptor:

discard(...)
    Remove an element from a set if it is a member.
    
    If the element is not a member, do nothing.



In [9]:
import numpy as np

In [10]:
np.array([1,2])

array([1, 2])

In [12]:
list(range(1,49,2))

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47]

In [17]:
np.linspace(1,50,25,dtype=int)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 50])

In [18]:
a = np.arange(1, 5)
np.power(a,2).sum()

30

In [19]:
np.add(a,np.arange(4))

array([1, 3, 5, 7])

In [1]:
import requests

In [15]:
r = requests.get(' https://api.douban.com/v2/book/27131703')

In [17]:
r=r.json()

In [19]:
print(r)

{'rating': {'max': 10, 'numRaters': 181, 'average': '7.0', 'min': 0}, 'subtitle': '未来社会的9大生存原则', 'author': ['[美] 伊藤穰一', '[美] 杰夫·豪'], 'pubdate': '2017-9-1', 'tags': [{'count': 111, 'name': '思维', 'title': '思维'}, {'count': 78, 'name': '互联网', 'title': '互联网'}, {'count': 73, 'name': '趋势', 'title': '趋势'}, {'count': 59, 'name': '罗辑思维', 'title': '罗辑思维'}, {'count': 47, 'name': '新经济', 'title': '新经济'}, {'count': 35, 'name': '颠覆', 'title': '颠覆'}, {'count': 34, 'name': '*北京·中信出版社*', 'title': '*北京·中信出版社*'}, {'count': 32, 'name': '管理', 'title': '管理'}], 'origin_title': '', 'image': 'https://img1.doubanio.com/mpic/s29539567.jpg', 'binding': '精装', 'translator': ['张培', '吴建英', '周卓斌'], 'catalog': '序言\n第一章 涌现优于权威\n第二章 拉力优于推力\n第三章 指南针优于地图\n第四章 风险优于安全\n第五章 违抗优于服从\n第七章 多样性优于能力\n第八章 韧性优于力量\n第九章 系统优于个体\n总结 致谢 注释', 'ebook_url': 'https://read.douban.com/ebook/40660459/', 'pages': '344', 'images': {'small': 'https://img1.doubanio.com/spic/s29539567.jpg', 'large': 'https://img1.doubanio.com/lpic/s29539567.jpg', 'medi

In [48]:
url = 'https://api.douban.com/v2/movie/subject/1291546'

In [49]:
r = requests.get(url)

In [51]:
r.json()

{'aka': ['再见，我的妾', 'Farewell My Concubine'],
 'alt': 'https://movie.douban.com/subject/1291546/',
 'casts': [{'alt': 'https://movie.douban.com/celebrity/1003494/',
   'avatars': {'large': 'https://img1.doubanio.com/img/celebrity/large/67.jpg',
    'medium': 'https://img1.doubanio.com/img/celebrity/medium/67.jpg',
    'small': 'https://img1.doubanio.com/img/celebrity/small/67.jpg'},
   'id': '1003494',
   'name': '张国荣'},
  {'alt': 'https://movie.douban.com/celebrity/1050265/',
   'avatars': {'large': 'https://img3.doubanio.com/img/celebrity/large/46345.jpg',
    'medium': 'https://img3.doubanio.com/img/celebrity/medium/46345.jpg',
    'small': 'https://img3.doubanio.com/img/celebrity/small/46345.jpg'},
   'id': '1050265',
   'name': '张丰毅'},
  {'alt': 'https://movie.douban.com/celebrity/1035641/',
   'avatars': {'large': 'https://img1.doubanio.com/img/celebrity/large/1399268395.47.jpg',
    'medium': 'https://img1.doubanio.com/img/celebrity/medium/1399268395.47.jpg',
    'small': 'https:

In [52]:
import nltk

In [53]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [54]:
from nltk.corpus import gutenberg

In [55]:
import nltk

In [56]:
print(gutenbergbergbergbergbergbergbergbergbergberg.fileids())

['austen-emma.txt', 'austen-persuasion.txt', 'austen-sense.txt', 'bible-kjv.txt', 'blake-poems.txt', 'bryant-stories.txt', 'burgess-busterbrown.txt', 'carroll-alice.txt', 'chesterton-ball.txt', 'chesterton-brown.txt', 'chesterton-thursday.txt', 'edgeworth-parents.txt', 'melville-moby_dick.txt', 'milton-paradise.txt', 'shakespeare-caesar.txt', 'shakespeare-hamlet.txt', 'shakespeare-macbeth.txt', 'whitman-leaves.txt']


In [58]:
# -*- coding: utf-8 -*-
"""
Get djidf
 
@author: Dazhuang
"""
 
import requests
import re
import pandas as pd
 
def retrieve_dji_list():
    r = requests.get('http://money.cnn.com/data/dow30/')
    search_pattern = re.compile('class="wsod_symbol">(.*?)<\/a>.*?<span.*?">(.*?)<\/span>.*?\n.*?class="wsod_stream">(.*?)<\/span>')
    dji_list_in_text = re.findall(search_pattern, r.text)
    dji_list = []
    for item in dji_list_in_text:
        dji_list.append([item[0], item[1], float(item[2])])
    return dji_list
 
dji_list = retrieve_dji_list()
djidf = pd.DataFrame(dji_list)
print(djidf)

       0                        1       2
0    MMM                       3M  203.56
1    AXP         American Express   86.14
2   AAPL                    Apple  164.05
3     BA                   Boeing  240.33
4    CAT              Caterpillar  118.28
5    CVX                  Chevron  108.76
6   CSCO                    Cisco   32.30
7     KO                Coca-Cola   45.78
8    DIS                   Disney  101.50
9    XOM              Exxon Mobil   76.57
10    GE         General Electric   25.14
11    GS            Goldman Sachs  225.88
12    HD               Home Depot  150.78
13   IBM                      IBM  144.08
14  INTC                    Intel   35.09
15   JNJ        Johnson & Johnson  131.03
16   JPM           JPMorgan Chase   91.70
17   MCD               McDonald's  159.81
18   MRK                    Merck   63.83
19  MSFT                Microsoft   73.94
20   NKE                     Nike   53.36
21   PFE                   Pfizer   33.96
22    PG         Procter & Gamble 